# This workflow builds and publishes the Python package to PyPI when a tag is pushed

name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v0.1.0, v1.2.3, etc.

jobs:
  deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
      # If you have build-specific dependencies, install them here
      # pip install -r requirements-build.txt

    - name: Build package
      run: python -m build

    - name: Publish package to PyPI using trusted publishing
      uses: pypa/gh-action-pypi-publish@release/v1
      # This action uses PyPI's OIDC trusted publishing.
